"""autogenerate models

Revision ID: a3d2cfc0f115
Revises: 0d08371166eb
Create Date: 2026-06-23 14:20:01.735857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d2cfc0f115'
down_revision: Union[str, Sequence[str], None] = '0d08371166eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This migration was autogenerated but left intentionally empty because
    # the initial schema migration (1a3b92bb5acb) creates tables directly
    # from the models. No additional operations are required here.
    return


def downgrade() -> None:
    """Downgrade schema."""
    return
